"""Fixed date redundancy

Revision ID: ccc9627f3a20
Revises: 0650b30b287f
Create Date: 2019-12-19 14:45:46.686171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccc9627f3a20'
down_revision = '0650b30b287f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'year')
    op.drop_column('item', 'day')
    op.drop_column('item', 'month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
