---
- name: Setup homeBrain for production use.
  hosts: ubuntu
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Ensure nginx is installed.
      package:
        name: nginx-core
        state: present

    - name: Ensure virtualenv is installed.
      package:
        name: python3-venv
        state: present
    
    - name: Ensure pip is installed.
      package:
        name: python3-pip
        state: present
  
    - name: Clone the repository.
      become: false
      git:
        repo: https://github.com/TSC-Apps/homeBrain.git
        dest: /home/ubuntu/homeBrain
        version: master
      
    - name: Create a virtualenv.
      become: false
      command: python3 -m venv /home/ubuntu/homeBrain/venv
      args:
        creates: /home/ubuntu/homeBrain/venv

    - name: Install packages into virtualenv.
      become: false
      pip: 
        requirements: /home/ubuntu/homeBrain/requirements.txt
        virtualenv: /home/ubuntu/homeBrain/venv

    - name: Copy systemd service file.
      copy:
        src: /home/ubuntu/homeBrain/homeBrain.service
        dest: /etc/systemd/system/
        remote_src: yes

    - name: Ensure homeBrain service is started.
      service:
        name: homeBrain
        state: started
    
    - name: Ensure homeBrain service is enabled.
      service:
        name: homeBrain
        enabled: yes

    - name: Remove default Nginx configuration.
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: Copy nginx configuration.
      copy:
        src: /home/ubuntu/homeBrain/homeBrain.sites-available
        dest: /etc/nginx/sites-available
        remote_src: yes

    - name: Enable Nginx site.
      file:
        src: /etc/nginx/sites-available/homeBrain.sites-available
        dest: /etc/nginx/sites-enabled/homeBrain.sites-available
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted